---
- name: reverse-proxy - setup network
  docker_network:
    name: reverse-proxy
    ipam_config:
      - subnet: 172.19.0.0/16
        gateway: 172.19.0.1

- name: openvpn-client
  import_tasks:
    file: openvpn-client.yml

- name: nzbget
  import_tasks:
    file: nzbget.yml

- name: lidarr
  import_tasks:
    file: lidarr.yml

- name: qbittorrent
  import_tasks:
    file: qbittorrent.yml

- name: radarr
  import_tasks:
    file: radarr.yml

- name: sonarr
  import_tasks:
    file: sonarr.yml

- name: avahi
  import_tasks:
    file: avahi.yml

- name: samba
  import_tasks:
    file: samba.yml

- name: plex
  import_tasks:
    file: plex.yml

- name: tautulli
  import_tasks:
    file: tautulli.yml

- name: unmanic
  import_tasks:
    file: unmanic.yml

- name: nginx
  import_tasks:
    file: nginx.yml

- name: plex-cleaner
  import_tasks:
    file: plex-cleaner.yml

- name: certbot
  import_tasks:
    file: certbot.yml

- name: prune
  docker_prune:
    containers: true
    images: true
    volumes: true
