---
- name: makemkv - pull and configure
  docker_container:
    name: makemkv
    image: jlesage/makemkv
    pull: true
    env:
      USER_ID: "65534"
      GROUP_ID: "65534"
    volumes:
      - /opt/config/makemkv:/config:rw
      - /data/shares/Media:/output:rw
      - /data/shares/Downloads:/storage:rw
    restart_policy: always
