---
- name: nginx - pull and configure
  docker_container:
    name: nginx
    image: nginx
    pull: true
    ports:
      - "80:80"
      - "443:443"
    links:
      - openvpn-client:lidarr
      - openvpn-client:radarr
      - openvpn-client:nzbget
      - openvpn-client:sonarr
      - openvpn-client:qbittorrent
      - tautulli:tautulli
      - unmanic:unmanic
    volumes:
      - /opt/config/nginx:/etc/nginx:rw
    restart_policy: always

- name: nginx - setup cronjob to regularly restart
  cron:
    name: Restart Nginx
    minute: "15"
    hour: "3"
    job: "docker exec -it nginx nginx -s reload >> /var/log/certbot.log"
