---
- name: openvpn-client - pull and configure
  docker_container:
    name: openvpn-client
    image: dperson/openvpn-client
    pull: true
    networks:
      - name: reverse-proxy
    capabilities:
      - net_admin
    devices:
      - /dev/net/tun:/dev/net/tun:rwm
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /opt/config/openvpn/client:/vpn:ro
    privileged: true
    restart_policy: always
