---
- name: Install gpg
  package:
    name: gpg
    state: present

- name: Install fastfetch
  package:
    name: fastfetch
    state: present

- name: Install intel-gpu-tools
  package:
    name: intel-gpu-tools
    state: present

- name: Install net-tools
  package:
    name: net-tools
    state: present

- name: Install speedtest-cli
  package:
    name: speedtest-cli
    state: present

- name: Install unrar
  package:
    name: unrar
    state: present

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Install zsh
  package:
    name: zsh
    state: present

- name: Allow passwordless sudo for 'sudo' group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo\tALL'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: '/usr/sbin/visudo -cf %s'
